version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
    # restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sgo-network
    healthcheck:
      # https://www.rabbitmq.com/monitoring.html#health-checks
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  zipkin-server:
    image: openzipkin/zipkin:2.23
    container_name: zipkin-server
    deploy:
      resources:
        limits:
          memory: 256M
    # restart: always
    ports:
      - "9411:9411"
    environment:
      # https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/rabbitmq
      - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    networks:
      - sgo-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  naming-server:
    # image: thiaguten/naming-server:0.0.1-SNAPSHOT
    # https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image
    build: ./naming-server/build/docker
    container_name: naming-server
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8761:8761"
    networks:
      - sgo-network

#  localizacao-service:
#    # image: thiaguten/localizacao-service:0.0.1-SNAPSHOT
#    # https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image
#    build: ./localizacao-service/build/docker
#    container_name: localizacao-service
#    deploy:
#      resources:
#        limits:
#          memory: 512M
#    ports:
#      - "8000:8000"
#    environment:
#      - PROFILE_CONFIG=docker
#      - SPRING_PROFILES_ACTIVE=docker
#      # - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
#      ## - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
#      # - SPRING.ZIPKIN.SENDER.TYPE=rabbit
#      # - SPRING.RABBITMQ.HOST=rabbitmq
#      # - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
#    networks:
#      - sgo-network
#    depends_on:
#      - naming-server
#      - rabbitmq

networks:
  sgo-network: