INSERT INTO SERVICO (NOME) VALUES ('Tapa Buraco');
INSERT INTO SERVICO (NOME) VALUES ('Caça Vazamento');
INSERT INTO ATENDENTE (ID) VALUES (1);
INSERT INTO ATENDENTE_IDENTIFICADO (ATENDENTE_ID, MATRICULA, NOME) VALUES (1, '1', 'Thiago Costa');