@startuml SGO_C4_Code

skinparam packageStyle folder
skinparam groupInheritance 2

title SGO - Diagrama de Código

circle ApiRESTfulLocalizacao
circle ApiRESTfulUsuario
circle ApiRESTfulServico
circle ApiRESTfulOcorrencia

namespace br.com.thiaguten.microservices.localizacaoservice #FFFFFF {

    class CEPUtils
    class CEPClientConfig
    interface CEPClientAPI
    class CEPClientAPIImpl
    class CEPClientAPIResponse
    class CEPClientAPIException
    
    class EnderecoDTO
    class EnderecoController
    class EnderecoModelAssembler
    interface EnderecoService
    class EnderecoServiceImpl
    interface EnderecoRepository
    class EnderecoInMemoryRepository
    class EnderecoNotFoundException
    
    class WebClientConfig
    class WebClientFilters
    class HttpStatusException

    class LocalizacaoServiceApplication

    .ApiRESTfulLocalizacao -- EnderecoController

    WebClientFilters <.. WebClientConfig
    WebClientFilters <.. CEPClientAPIImpl
    HttpStatusException <.. WebClientFilters : <<create>>
    
    CEPUtils <.. CEPClientAPIImpl
    CEPUtils <.. EnderecoModelAssembler
    CEPUtils <.. EnderecoInMemoryRepository
    CEPClientAPI <|.. CEPClientAPIImpl
    CEPClientAPI <.. EnderecoServiceImpl
    CEPClientAPI "1" <--o "1" EnderecoServiceImpl
    CEPClientAPIResponse <.. CEPClientAPIImpl
    CEPClientAPIException <.. CEPClientAPIImpl
    
    EnderecoDTO <.. EnderecoController : <<create>>
    EnderecoDTO <.. EnderecoModelAssembler
    EnderecoDTO <.. EnderecoService
    EnderecoDTO <.. EnderecoServiceImpl : <<create>>
    EnderecoDTO <.. EnderecoRepository
    EnderecoDTO <.. EnderecoInMemoryRepository
    EnderecoDTO <.. CEPClientAPI
    EnderecoDTO <.. CEPClientAPIImpl : <<create>>
    
    EnderecoModelAssembler <..> EnderecoController
    EnderecoModelAssembler "1" <--o "1" EnderecoController
    EnderecoService <|.. EnderecoServiceImpl
    EnderecoService <.. EnderecoController
    EnderecoService "1" <--o "1" EnderecoController
    EnderecoRepository <|.. EnderecoInMemoryRepository
    EnderecoRepository <.. EnderecoServiceImpl
    EnderecoRepository "1" <--o "1" EnderecoServiceImpl
}

namespace br.com.thiaguten.microservices.ocorrenciaservice #FFFFFF {
    
    class KeycloakService
    class KeycloakIntegrationException
    class KeycloakUserAlreadyExistsException

    class UsuarioIdentificado
    
    class Usuario
    class UsuarioDTO
    class UsuarioDTOMapper
    class UsuarioModelAssembler
    class UsuarioController
    interface UsuarioService
    class UsuarioServiceImpl
    interface UsuarioRepository
    class UsuarioNotFoundException

    class Ocorrencia
    class OcorrenciaDTO
    class OcorrenciaDTOMapper
    class OcorrenciaModelAssembler
    class OcorrenciaController
    interface OcorrenciaService
    class OcorrenciaServiceImpl
    interface OcorrenciaRepository
    class OcorrenciaNotFoundException
    
    class Atendente
    class AtendenteIdentificado
    class AtendimentoOcorrenciaPK
    class AtendimentoOcorrencia
    
    class Endereco

    class SituacaoOcorrencia
    class SituacaoOcorrenciaConverter
    class SituacaoOcorrenciaNotFoundException

    interface DTOMapper

    class Servico
    class ServicoDTO
    class ServicoDTOMapper
    class ServicoModelAssembler
    class ServicoController
    interface ServicoService
    class ServicoServiceImpl
    interface ServicoRepository
    class ServicoNotFoundException
    
    class SecurityResourceServerConfig
    class OcorrenciaServiceApplication
    class RolesAllowedConstants
    class KeycloakConfig
    class JacksonConfig

    .ApiRESTfulUsuario -- UsuarioController
    .ApiRESTfulServico -- ServicoController
    .ApiRESTfulOcorrencia -- OcorrenciaController

    KeycloakService <.. UsuarioController
    KeycloakService "1" <--o "1" UsuarioController
    KeycloakIntegrationException <.. KeycloakService : <<create>>
    KeycloakUserAlreadyExistsException <.. KeycloakService : <<create>>

    UsuarioIdentificado "1" <--o "1" Usuario
    UsuarioIdentificado <.. UsuarioDTOMapper : <<create>>

    Usuario <.. UsuarioController
    Usuario <.. UsuarioModelAssembler
    Usuario <.. UsuarioDTOMapper : <<create>>
    Usuario <.. UsuarioService
    Usuario <.. UsuarioServiceImpl
    Usuario <.. UsuarioRepository
    Usuario <.. Ocorrencia
    Usuario "1" <--o "1" Ocorrencia
    Usuario <.. OcorrenciaController
    Usuario <.. OcorrenciaService
    Usuario <.. OcorrenciaServiceImpl
    Usuario <..> UsuarioIdentificado
    Usuario "1" <--o "1" UsuarioIdentificado
    UsuarioModelAssembler <..> UsuarioController
    UsuarioModelAssembler "1" <--o "1" UsuarioController
    UsuarioService <|.. UsuarioServiceImpl
    UsuarioService <.. UsuarioController
    UsuarioService "1" <--o "1" UsuarioController
    UsuarioService <.. OcorrenciaController
    UsuarioService "1" <--o "1" OcorrenciaController
    UsuarioRepository <.. UsuarioServiceImpl
    UsuarioRepository "1" <--o "1" UsuarioServiceImpl
    UsuarioNotFoundException <.. UsuarioController : <<create>>
    UsuarioNotFoundException <.. UsuarioServiceImpl : <<create>>
    UsuarioNotFoundException <.. OcorrenciaController : <<create>>

    UsuarioDTO <.. KeycloakService
    UsuarioDTO <.. UsuarioController
    UsuarioDTO <..> UsuarioModelAssembler
    UsuarioDTO <.. UsuarioDTOMapper : <<create>>
    UsuarioDTOMapper <.. UsuarioController
    UsuarioDTOMapper "1" <--o "1" UsuarioController
    UsuarioDTOMapper <..> UsuarioModelAssembler
    UsuarioDTOMapper "1" <--o "1" UsuarioModelAssembler

    Atendente <..> AtendenteIdentificado
    Atendente "1" <--o "1" AtendenteIdentificado
    Atendente <.. AtendimentoOcorrencia
    Atendente "1" <--o "many" AtendimentoOcorrencia
    AtendenteIdentificado "1" <--o "1" Atendente
    AtendimentoOcorrenciaPK "1" <--o "1" AtendimentoOcorrencia
    AtendimentoOcorrenciaPK <.. AtendimentoOcorrencia : <<create>>
    AtendimentoOcorrencia <.. Atendente : <<create>>
    AtendimentoOcorrencia "many" <--o "1" Atendente
    AtendimentoOcorrencia <.. Ocorrencia
    AtendimentoOcorrencia "1" <--o "1" Ocorrencia
    
    Ocorrencia <.. AtendimentoOcorrencia
    Ocorrencia "1" <--o "1" AtendimentoOcorrencia
    Ocorrencia "1" <--o "1" Endereco
    Ocorrencia <.. OcorrenciaDTOMapper : <<create>>
    Ocorrencia <.. OcorrenciaController
    Ocorrencia <.. OcorrenciaModelAssembler
    Ocorrencia <.. OcorrenciaService
    Ocorrencia <.. OcorrenciaServiceImpl
    OcorrenciaModelAssembler <..> OcorrenciaController
    OcorrenciaModelAssembler "1" <--o "1" OcorrenciaController
    OcorrenciaService <|.. OcorrenciaServiceImpl
    OcorrenciaService <.. OcorrenciaController
    OcorrenciaService "1" <--o "1" OcorrenciaController
    OcorrenciaRepository <.. OcorrenciaServiceImpl
    OcorrenciaRepository "1" <--o "1" OcorrenciaServiceImpl
    OcorrenciaNotFoundException <.. OcorrenciaController : <<create>>
    
    OcorrenciaDTO <.. OcorrenciaController
    OcorrenciaDTO <.. OcorrenciaModelAssembler
    OcorrenciaDTO <.. OcorrenciaDTOMapper : <<create>>
    OcorrenciaDTOMapper <.. OcorrenciaController
    OcorrenciaDTOMapper "1" <--o "1" OcorrenciaController
    OcorrenciaDTOMapper <.. OcorrenciaModelAssembler
    OcorrenciaDTOMapper "1" <--o "1" OcorrenciaModelAssembler
    
    Endereco <..> Ocorrencia
    Endereco "1" <--o "1" Ocorrencia
    Endereco <.. OcorrenciaDTOMapper : <<create>>
    
    SituacaoOcorrencia <.. Ocorrencia
    SituacaoOcorrencia <.. OcorrenciaDTOMapper
    SituacaoOcorrencia <.. OcorrenciaController
    SituacaoOcorrencia <.. OcorrenciaModelAssembler
    SituacaoOcorrencia <.. SituacaoOcorrenciaConverter
    SituacaoOcorrenciaNotFoundException <.. SituacaoOcorrencia : <<create>>
    
    DTOMapper <|.. ServicoDTOMapper
    DTOMapper <|.. OcorrenciaDTOMapper
    DTOMapper <|.. UsuarioDTOMapper

    Servico <.. ServicoController
    Servico <.. ServicoService
    Servico <.. ServicoRepository
    Servico <.. ServicoModelAssembler
    Servico <.. ServicoDTOMapper : <<create>>
    Servico <.. Ocorrencia
    Servico "1" <--o "1" Ocorrencia
    Servico <.. OcorrenciaDTOMapper
    Servico "1" <--o "1" OcorrenciaDTOMapper
    ServicoModelAssembler <..> ServicoController
    ServicoModelAssembler "1" <--o "1" ServicoController
    ServicoService <|.. ServicoServiceImpl
    ServicoService <.. OcorrenciaDTOMapper
    ServicoService "1" <--o "1" OcorrenciaDTOMapper
    ServicoService <.. ServicoController
    ServicoService "1" <--o "1" ServicoController
    ServicoRepository <.. ServicoServiceImpl
    ServicoRepository "1" <--o "1" ServicoServiceImpl
    ServicoNotFoundException <.. ServicoController : <<create>>
    
    ServicoDTO <.. ServicoController
    ServicoDTO <.. ServicoModelAssembler
    ServicoDTO <.. ServicoDTOMapper : <<create>>
    ServicoDTOMapper <.. ServicoController
    ServicoDTOMapper "1" <--o "1" ServicoController
    ServicoDTOMapper <.. ServicoModelAssembler
    ServicoDTOMapper "1" <--o "1" ServicoModelAssembler
}

' namespace br.com.thiaguten.microservices.notificacaoservice #FFFFFF {
    
' }

' namespace br.com.thiaguten.microservices.relatorioservice #FFFFFF {
    
' }

@enduml