@startuml SGO_C4_Code

skinparam packageStyle folder
skinparam groupInheritance 2

title SGO - Diagrama de Código

circle ApiRESTfulLocalizacao
circle ApiRESTfulUsuario
circle ApiRESTfulServico
circle ApiRESTfulOcorrencia

namespace br.com.thiaguten.microservices.localizacaoservice #FFFFFF {

    class CEPUtils
    class EnderecoDTO
    class CEPClientAPIResponse
    class CEPClientAPIException
    interface CEPClientAPI
    class CEPClientAPIImpl
    interface EnderecoRepository
    class EnderecoInMemoryRepository 
    interface EnderecoService
    class EnderecoServiceImpl
    class EnderecoModelAssembler
    class EnderecoController
    class HttpStatusException
    class WebClientFilters
    class WebClientConfig
    class CEPClientConfig
    class EnderecoNotFoundException
    class LocalizacaoServiceApplication

    .ApiRESTfulLocalizacao -- EnderecoController

    WebClientFilters <.. WebClientConfig
    HttpStatusException <.. WebClientFilters : <<create>>
    CEPClientAPI <|.. CEPClientAPIImpl
    CEPUtils <.. CEPClientAPIImpl
    CEPClientAPIResponse <.. CEPClientAPIImpl
    EnderecoDTO <.. CEPClientAPIImpl : <<create>>
    WebClientFilters <.. CEPClientAPIImpl
    CEPClientAPIException <.. CEPClientAPIImpl
    EnderecoRepository <|.. EnderecoInMemoryRepository
    EnderecoDTO <.. EnderecoInMemoryRepository
    CEPUtils <.. EnderecoInMemoryRepository
    EnderecoDTO <.. EnderecoRepository
    EnderecoRepository <.. EnderecoServiceImpl
    EnderecoRepository "1" <--o "1" EnderecoServiceImpl
    CEPClientAPI <.. EnderecoServiceImpl
    CEPClientAPI "1" <--o "1" EnderecoServiceImpl
    EnderecoService <|.. EnderecoServiceImpl
    EnderecoDTO <.. EnderecoServiceImpl : <<create>>
    EnderecoDTO <.. EnderecoService
    EnderecoDTO <.. EnderecoModelAssembler
    CEPUtils <.. EnderecoModelAssembler
    EnderecoDTO <.. EnderecoController : <<create>>
    EnderecoService <.. EnderecoController
    EnderecoService "1" <--o "1" EnderecoController
    EnderecoModelAssembler <..> EnderecoController
    EnderecoModelAssembler "1" <--o "1" EnderecoController
    EnderecoDTO <.. CEPClientAPI
}

namespace br.com.thiaguten.microservices.ocorrenciaservice #FFFFFF {
    
    class KeycloakService
    class KeycloakIntegrationException
    class KeycloakUserAlreadyExistsException
    class Usuario
    class UsuarioIdentificado
    class UsuarioDTO
    class UsuarioDTOMapper
    class UsuarioModelAssembler
    class UsuarioController
    interface UsuarioService
    class UsuarioServiceImpl
    interface UsuarioRepository
    class UsuarioNotFoundException
    class Ocorrencia
    class OcorrenciaController
    interface OcorrenciaService
    class OcorrenciaServiceImpl
    interface OcorrenciaRepository
    class OcorrenciaDTO
    class OcorrenciaDTOMapper
    class OcorrenciaNotFoundException
    class OcorrenciaModelAssembler
    class Atendente
    class AtendenteIdentificado
    class AtendimentoOcorrencia
    class AtendimentoOcorrenciaPK
    class Endereco
    class SituacaoOcorrencia
    class SituacaoOcorrenciaConverter
    class SituacaoOcorrenciaNotFoundException
    interface DTOMapper
    class Servico
    interface ServicoService
    class ServicoServiceImpl
    class ServicoDTO
    class ServicoDTOMapper
    class ServicoController
    class ServicoNotFoundException
    class ServicoModelAssembler
    interface ServicoRepository
    class SecurityResourceServerConfig
    class OcorrenciaServiceApplication
    class RolesAllowedConstants
    class KeycloakConfig
    class JacksonConfig

    .ApiRESTfulUsuario -- UsuarioController
    .ApiRESTfulServico -- ServicoController
    .ApiRESTfulOcorrencia -- OcorrenciaController

    KeycloakIntegrationException <.. KeycloakService : <<create>>
    KeycloakUserAlreadyExistsException <.. KeycloakService : <<create>>
    UsuarioDTO <.. KeycloakService
    Usuario <.. UsuarioController
    UsuarioDTO <.. UsuarioController
    UsuarioDTOMapper <.. UsuarioController
    UsuarioService <.. UsuarioController
    UsuarioNotFoundException <.. UsuarioController : <<create>>
    KeycloakService <.. UsuarioController
    KeycloakService "1" <--o "1" UsuarioController
    UsuarioDTOMapper "1" <--o "1" UsuarioController
    UsuarioService "1" <--o "1" UsuarioController
    UsuarioModelAssembler "1" <--o "1" UsuarioController
    UsuarioModelAssembler <..> UsuarioController
    Usuario <.. UsuarioModelAssembler
    UsuarioDTO <..> UsuarioModelAssembler
    UsuarioDTOMapper <..> UsuarioModelAssembler
    UsuarioDTOMapper "1" <--o "1" UsuarioModelAssembler
    Usuario <.. UsuarioDTOMapper : <<create>>
    UsuarioIdentificado <.. UsuarioDTOMapper : <<create>>
    UsuarioDTO <.. UsuarioDTOMapper : <<create>>
    Usuario <.. UsuarioRepository
    UsuarioRepository <.. UsuarioServiceImpl
    UsuarioRepository "1" <--o "1" UsuarioServiceImpl
    Usuario <.. UsuarioService
    Usuario <.. UsuarioServiceImpl
    UsuarioService <|.. UsuarioServiceImpl
    UsuarioNotFoundException <.. UsuarioServiceImpl : <<create>>
    UsuarioService <.. OcorrenciaController
    UsuarioService "1" <--o "1" OcorrenciaController
    Usuario <..> UsuarioIdentificado
    Usuario "1" <--o "1" UsuarioIdentificado
    UsuarioIdentificado "1" <--o "1" Usuario
    Usuario "1" <--o "1" Ocorrencia
    Usuario <.. Ocorrencia
    Usuario <.. OcorrenciaController
    Usuario <.. OcorrenciaService
    Usuario <.. OcorrenciaServiceImpl
    OcorrenciaService <|.. OcorrenciaServiceImpl
    UsuarioNotFoundException <.. OcorrenciaController : <<create>>
    Atendente <..> AtendenteIdentificado
    Atendente "1" <--o "1" AtendenteIdentificado
    AtendenteIdentificado "1" <--o "1" Atendente
    AtendimentoOcorrenciaPK "1" <--o "1" AtendimentoOcorrencia
    AtendimentoOcorrenciaPK <.. AtendimentoOcorrencia : <<create>>
    Atendente <.. AtendimentoOcorrencia
    Ocorrencia <.. AtendimentoOcorrencia
    AtendimentoOcorrencia <.. Ocorrencia
    AtendimentoOcorrencia <.. Atendente : <<create>>
    AtendimentoOcorrencia "many" <--o "1" Atendente
    Atendente "1" <--o "many" AtendimentoOcorrencia
    AtendimentoOcorrencia "1" <--o "1" Ocorrencia
    Ocorrencia "1" <--o "1" AtendimentoOcorrencia
    OcorrenciaRepository <.. OcorrenciaServiceImpl
    OcorrenciaRepository "1" <--o "1" OcorrenciaServiceImpl
    Ocorrencia <.. OcorrenciaServiceImpl
    Ocorrencia <.. OcorrenciaService
    OcorrenciaService <.. OcorrenciaController
    OcorrenciaService "1" <--o "1" OcorrenciaController
    OcorrenciaNotFoundException <.. OcorrenciaController : <<create>>
    Ocorrencia <.. OcorrenciaController
    OcorrenciaModelAssembler <.. OcorrenciaController
    OcorrenciaModelAssembler "1" <--o "1" OcorrenciaController
    OcorrenciaDTO <.. OcorrenciaController
    SituacaoOcorrencia <.. OcorrenciaController
    OcorrenciaDTOMapper <.. OcorrenciaController
    OcorrenciaDTOMapper "1" <--o "1" OcorrenciaController
    Endereco <..> Ocorrencia
    Endereco "1" <--o "1" Ocorrencia
    Ocorrencia "1" <--o "1" Endereco
    Endereco <.. OcorrenciaDTOMapper : <<create>>
    Ocorrencia <.. OcorrenciaDTOMapper : <<create>>
    OcorrenciaDTO <.. OcorrenciaDTOMapper : <<create>>
    OcorrenciaDTOMapper <.. OcorrenciaModelAssembler
    OcorrenciaDTOMapper "1" <--o "1" OcorrenciaModelAssembler
    SituacaoOcorrencia <.. OcorrenciaModelAssembler
    OcorrenciaDTO <.. OcorrenciaModelAssembler
    Ocorrencia <.. OcorrenciaModelAssembler
    SituacaoOcorrenciaNotFoundException <.. SituacaoOcorrencia : <<create>>
    SituacaoOcorrencia <.. Ocorrencia
    SituacaoOcorrencia <.. OcorrenciaDTOMapper
    SituacaoOcorrencia <.. SituacaoOcorrenciaConverter
    DTOMapper <|.. OcorrenciaDTOMapper
    DTOMapper <|.. UsuarioDTOMapper
    Servico <.. OcorrenciaDTOMapper
    Servico "1" <--o "1" OcorrenciaDTOMapper
    Servico <.. Ocorrencia
    Servico "1" <--o "1" Ocorrencia
    ServicoService <.. OcorrenciaDTOMapper
    ServicoService "1" <--o "1" OcorrenciaDTOMapper
    ServicoNotFoundException <.. ServicoController : <<create>>
    Servico <.. ServicoController
    ServicoDTO <.. ServicoController
    ServicoDTOMapper <.. ServicoController
    ServicoDTOMapper "1" <--o "1" ServicoController
    ServicoService <.. ServicoController
    ServicoService "1" <--o "1" ServicoController
    ServicoModelAssembler "1" <--o "1" ServicoController
    ServicoModelAssembler <.. ServicoController
    ServicoController <.. ServicoModelAssembler
    Servico <.. ServicoModelAssembler
    ServicoDTO <.. ServicoModelAssembler
    ServicoDTOMapper <.. ServicoModelAssembler
    ServicoDTOMapper "1" <--o "1" ServicoModelAssembler
    DTOMapper <|.. ServicoDTOMapper
    Servico <.. ServicoDTOMapper : <<create>>
    ServicoDTO <.. ServicoDTOMapper : <<create>>
    ServicoService <|.. ServicoServiceImpl
    ServicoRepository <.. ServicoServiceImpl
    ServicoRepository "1" <--o "1" ServicoServiceImpl
    Servico <.. ServicoRepository
    Servico <.. ServicoService
}

' namespace br.com.thiaguten.microservices.notificacaoservice #FFFFFF {
    
' }

' namespace br.com.thiaguten.microservices.relatorioservice #FFFFFF {
    
' }

@enduml